### ISSUE TITLE
poll() works only if stdout or stderr is pipe

### ISSUE THREAD

**Issue by wch** [r-lib/processx#101]
For example:

```R
p <- processx::process$new("sleep", "5", stdout="|")
poll(list(p), 10000)  # Waits for 5 seconds


p <- processx::process$new("sleep", "5")
poll(list(p), 10000)  # Returns immediately
```

It also doesn't work when stdout is written to a file, which is my current use case.

The help says:
> poll() cannot wait on the termination of a process directly. It is only signalled through the closed stdout and stderr pipes. 

Couldn't it actually poll to see if the processes are still running?

If it's not possible to make `poll()` work when stdout isn't a pipe, then it be helpful to:
* Say that in the documentation
* Throw an error when `poll()` is called with process objects that don't use pipes.

**Comment by gaborcsardi** [comment]
> Couldn't it actually poll to see if the processes are still running?

In Unix you can only poll file descriptors, not processes.

>I f it's not possible to make poll() work when stdout isn't a pipe, then it be helpful to:
> Say that in the documentation

Yes, that's what that quoted part was trying to say.  Basically, polling is for I/O. If you want to wait for a process to finish, you can use `$wait()`

> Throw an error when poll() is called with process objects that don't use pipes.

You can see that in the result:
```r
❯ p <- processx::process$new("sleep", "5")
❯ poll(list(p), 10000)  # Returns immediately
[[1]]
  output    error
"nopipe" "nopipe"
```

An error is not a good solution here, because that would be a special case. I.e. `poll()` should work on an empty list as well.

**Comment by gaborcsardi** [comment]
All this said, you are right that we need a way to "poll" a process that does not have I/O pipes, so that  we can use these processes in an event loop. I am planning to add this.

**Comment by wch** [comment]
> Yes, that's what that quoted part was trying to say. Basically, polling is for I/O. If you want to wait for a process to finish, you can use `$wait()`

My use case is that I want to start two processes and wait until they both exit, with a specified timeout. I suppose that would be possible with something roughly like this,  but it's not very elegant:

```
p1 <- process$new(....)
p2 <- process$new(....)

start <- as.numeric(Sys.time())
end <- start + 10
p1$wait(end - as.numeric(Sys.time()))
p2$wait(end - as.numeric(Sys.time()))
```

**Comment by gaborcsardi** [comment]
Yeah, I think that's the best workaround currently. 

Unfortunately on Unix, a process does not really have a handle that you can manipulate. Even `$wait()` with a timeout is a hack, because the original `wait*` systems calls don't support timeouts.

It is possible to make this work, however, event though it is not easy. We need to open another pipe to the child process and poll on that. It will generate an event when the process finishes. Hopefully this will not cause problems in the child, we'll make it as close-on-exec.

I need this extra connection, actually, for another use case, so I'll work on this soon.
