### ISSUE TITLE
Allow serializing process object to a file

### ISSUE THREAD

**Issue by matthijsvanderloos** [r-lib/processx#135]
I'm looking for solution to create processes in an R application and after a restart of R to be able to check if processes are still running/finished, etc. For example:

```R
# save 
saveRDS(p, file = "process.rds")
# load after R restart
p <- readRDS("process.rds")
p
```
As this point R crashes as there are null pointers in the restored `p` object. Any chance there will be a possiblity to store `process` objects?

**Comment by gaborcsardi** [comment]
This is not possible, because the file descriptors will be closed when the process exits, so when you unserialize the object, you cannot use them. So many of the methods  would not work after serialization.

If you don't need the stdout, stderr, etc. connections, polling, etc. then you can save the process pid  and start time (`$get_start_time()`, coming  to the CRAN version soon), and then the new ps package (https://github.com/r-lib/ps, submitted to CRAN) to manage the processes. Of course you won't  (easily) be able to poll the process, read stdout, etc.
