### ISSUE TITLE
Small tip: making sure processes exit after user interrupt

### ISSUE THREAD

**Issue by rickhelmus** [r-lib/processx#171]
Hello,

Not a bug report, just an FYI as I couldn't find anything about this elsewhere (please correct me if I'm wrong though!).

At the moment (sub)processes are not cleaned up after user interruption (e.g. pressing the 'stop' button). A simple workaround is to wrap the code in `tryCatch` and call `gc()` in case an interruption occurs:
```R
tryCatch(doYourProcessxThing(), interrupt = function(e) gc(verbose = FALSE))

# or to suppress output from gc()
tryCatch(doYourProcessxThing(), interrupt = function(e) invisible(capture.output(gc(verbose = FALSE))))
```

Cheers,
Rick

**Comment by gaborcsardi** [comment]
Is this about `run()`? Because `run()` subprocesses are cleaned up after an interrupt.

If you create background processes, then yes, those cannot be cleaned up on an interrupt.

Unfortunately your code also "handles" the interrupt, and you don't go back to top level. E.g. (on Unix)

```r
f <- function() {
  p <- processx::process$new("sleep", "100")
  Sys.sleep(50)
  print("This is not printed")
}
f()  ## interrupt this, then run: 
ps::ps_children(ps::ps_handle())
```

```r
f2 <- function() {
  tryCatch({
    p <- processx::process$new("sleep", "100")
    Sys.sleep(50) },
    interrupt = function(e) p$kill())
  print("This is printed")
}
gc()
f2()  ## interrupt this, then run:
ps::ps_children(ps::ps_handle())
```

I would think that most often this is not the interrupt behavior you want, but you want to go back to top level, i.e. to the prompt in an interactive session.

You get the usual interruption semantics with

```r
f3 <- function() {
  tryCatch({
    p <- processx::process$new("sleep", "100")
    Sys.sleep(50) }, 
    interrupt = function(e) { p$kill(); invokeRestart("abort") })
  print("This is not printed")
}
gc()
f3()  ## interrupt this, then run:
ps::ps_children(ps::ps_handle())
```

Instead of `p$kill()` you can also `gc()`, but then don't forget to remove the process objects first,  i.e. `p` in the example.

**Comment by rickhelmus** [comment]
Excellent! Thanks for this, I didn't realize that. It is indeed for background processes, sorry to not mention that.

(PS: I guess the reason I didn't need to manually clearout the process handler (`p` in your examples) before garbage collection is because my code is executed in another function.)

**Comment by gaborcsardi** [comment]
Actually, my code is not completely correct, still. You also need to re-throw the interrupt, in case upstream code catches it. E.g. this is how `run()` does this:

        interrupt = function(e) {
            tryCatch(pr$kill(), error = function(e) NULL)
            signalCondition(make_condition(list(interrupt = TRUE), runcall))
            cat("\n")
            invokeRestart("abort")
        })

Instead of making a special condition, like in `make_condition()`, I think you can  just re-throw the original condition object, `e`.

**Comment by rickhelmus** [comment]
Hi Gábor, thanks again.

Actually thinking a bit more about it - why not just a `finally` handler instead?
```R
f2 <- function() {
    tryCatch({
        p <- processx::process$new("sleep", "100")
        Sys.sleep(50) },
        finally = p$kill())
    print("This is printed") # not anymore!
}
gc()
f2()  ## interrupt this, then run:
ps::ps_children(ps::ps_handle())
```
This seems to yield the expected behavior. Wrapping this whole thing in another `tryCatch` it seems that the interrupt handler is still called as well.

**Comment by gaborcsardi** [comment]
Yeah, `finally` looks good. Another way would be `withCallingHandlers`, that is simpler than `tryCatch`, because you don't need to re-throw the condition.

**Comment by rickhelmus** [comment]
Unfortunately, I don't really understand why the condition needs to be re-thrown as I assumed `tryCatch` with merely a finally statement wouldn't install any handlers.

As I try to wrap around the apparent much more complex signalling system of R I thought it was (this is getting quite offtopic so please feel free to ignore).

The `f_*` functions sortof summarize a bit the above.
```R
doSleep <- function() {
    p <- processx::process$new("sleep", "100")
    Sys.sleep(50)
}

cleanUp <- function(...) { gc(); cat("Cleaned up!\n") }

f_tc1 <- function() {
    tryCatch(doSleep(), interrupt = function(e) { cleanUp(); signalCondition(e); invokeRestart("abort") } )
    print("This is printed")
}

f_tc2 <- function() {
    tryCatch(doSleep(), finally = cleanUp())
    print("This is printed")
}

f_wc1 <- function() {
    withCallingHandlers(doSleep(), interrupt = cleanUp)
    print("This is printed")
}

f_wc2 <- function() {
    withCallingHandlers(doSleep(), finally = cleanUp())
    print("This is printed")
}

funcs <- c(f_tc1, f_tc2, f_wc1, f_wc2)
for (i in seq_along(funcs)) {
    gc()
    cat(sprintf("func: %d\n", i))
    tryCatch(funcs[[i]](), interrupt = function(e) cat("Cought interruption!\n"))
    cat("Called after being catched!\n")
    print(ps::ps_children(ps::ps_handle()))
}
```
Their output:
```
func: 1
^CCleaned up!
Cought interruption!
Called after being catched!
list()
func: 2
^CCleaned up!
Cought interruption!
Called after being catched!
list()
func: 3
^CCleaned up!
Cought interruption!
Called after being catched!
[[1]]
<ps::ps_handle> PID=7718, NAME=sleep, AT=2019-01-10 21:14:37

func: 4
Cleaned up!
^CCought interruption!
Called after being catched!
[[1]]
<ps::ps_handle> PID=7719, NAME=sleep, AT=2019-01-10 21:14:38
```
Only the first two functions seem to behave as we want (I think? as they don't show any leftover processes).

Anyway, again, I don't want to bother too much with off-topic stuff as there is already a solution here, but otherwise I would be really interested in whats going on here :-)

**Comment by gaborcsardi** [comment]
If you use `withCallingHandlers()`, then you'll have to use the `$kill()` method, because `withCallingHandlers()` keep the complete function stack, so the `p` reference to the process object is still valid, and `gc()` will not clean it up. That's all that is happening here.

In the end, this is great, there are (at least) two good ways to solve this, `tryCatch()` + `gc()` / `$kill()`, but then you need to re-throw the interrupt condition, or `withCallingHandlers()` but then you need to use `$kill()` explicitly.

**Comment by gaborcsardi** [comment]
Actually, why don't we use `on.exit()` here?

**Comment by rickhelmus** [comment]
Seems to work! Not sure how I missed `on.exit`? Oh well ...
