### ISSUE TITLE
Support for glob patterns

### ISSUE THREAD

**Issue by peterlittlejohn** [r-lib/processx#213]
Hello, I love your package!

It would be great to have support for glob patterns; as in
`run("ls","abc*")`

What do you think?  (Or is there a reason that's not supported?)

**Comment by gaborcsardi** [comment]
The shell does the globbing, so if you want to glob, you need to call a shell. Of course this will not be portable any more, i.e. it'll not work if the chosen shell is not present on the system:

```r
❯ processx::run("sh", c("-c", "ls -d D*"))
$status
[1] 0

$stdout
[1] "Desktop\nDocuments\nDownloads\n"

$stderr
[1] ""

$timeout
[1] FALSE
```

**Comment by peterlittlejohn** [comment]
Thanks for your response and the code. 

That’s right and from reading your documentation, from what I remember, a key idea is to try to avoid opening a shell, for reasons of control more than portability.

But you could integrate a pattern matcher separately, no?

**Comment by gaborcsardi** [comment]
Hmmm, to be honest, I am not sure if this belongs in processx. R already has some limited globbing support via the `glob2rx()` function. There is a more complete implementation here: https://github.com/r-lib/remotes/blob/feature/untar/R/glob.R

It would probably make sense to have a function that works on the file system directly, instead of a vector of paths. This could be added to `glob.R`, which is designed as a standalone file that you can just copy into your package.

**Comment by peterlittlejohn** [comment]
Yes, you’re right—doesn’t belong inside processx. I’ll take a look at glob.R.
