### ISSUE TITLE
Windows: execution in background and cleanup 

### ISSUE THREAD

**Issue by filipporio** [r-lib/processx#214]
Hi,
I'm using processx on windows and I'm experiencing the following problem.

I've created a dummy test file, named test_process.R, containing only the following lines:

for (i in 1:60){
   print(i)
   Sys.sleep(1)
}

Then I try to source it using Rscript via processx, redirecting stdout and stderr on two separated files. I repeat the line twice, once specifying "cleanup=TRUE", once "cleanup=FALSE".

require(processx)
myrscript<-paste0(R.home(),"/bin/Rscript")
myproc1<-process$new(myrscript, "test_process.R",stdout="test1_out.txt",stderr="test1_err.txt",cleanup=TRUE)
myproc2<-process$new(myrscript, "test_process.R",stdout="test2_out.txt",stderr="test2_err.txt",cleanup=FALSE)

The first process runs in background and the stdout is correctly redirected on "test1_out.txt".
The second process runs in foreground in a new window and the file "test2_out.txt" is created but remains empty.

Is this an expected behaviour? How can I prevent the cleanup but run in background?
I'd like to report that on ubuntu and OSX this does not happen.

I attach the zip file with the two dummy R files, for reference.

Thanks in advance for your help

[myprocessx_test.zip](https://github.com/r-lib/processx/files/3387155/myprocessx_test.zip)

**Comment by gaborcsardi** [comment]
Yes, I can confirm this. It seems like a bug.

**Comment by gaborcsardi** [comment]
After taking a closer look, I don't think this is a bug, but `Rscript` simply decides to create a console. This is not up to processx, processsx starts it without a console.

I am not sure what exactly you are trying to do, but running R in the background is not trivial. Maybe you can use the callr package, or just take a look at it to see how things are implemented there.

**Comment by filipporio** [comment]
What I do not understand is why Rscript decides whether to open a console or not, depending on cleanup parameters.

My purpose, beyond the dummy use case I have shown here, is to launch a separate long r process after an API request, handled with rook.

What I experienced was the unexpected lack of content in the stdout file, but only if the cleanup option is set to false. That's why i wrote you.

**Comment by gaborcsardi** [comment]
> What I do not understand is why Rscript decides whether to open a console or not, depending on cleanup parameters.

Because if `cleanup = FALSE`, then the process is started with `DETACHED_PROCESS`, so the new process does not inherit the console. And then R notices that it has no console, and it creates one, which overrides the output redirection.

> My purpose, beyond the dummy use case I have shown here, is to launch a separate long r process after an API request, handled with rook.

I think the callr package will be probably more convenient for you. Maybe if you start `Rterm`, like callr does, that solves your issue.

This said, I am not convinced that this is the right behavior, I mean, using `DETACHED_PROCESS` for `cleanup = FALSE`. At least this could be a separate flag, I mean, the cleanup and the detaching. I can add that.

**Comment by filipporio** [comment]
I agree with you, maybe separate flags would be convenient.

However, thanks for your help and for your hint with callr, I will try asap.

**Comment by Hong-Revo** [comment]
I _think_ this is the same as something I just experienced.

I have a unit test that runs an external program using `processx::run` ([azcopy](https://github.com/Azure/azure-storage-azcopy) to be precise). The test works when I use `devtools::test()`, but it hangs under `devtools::check()`. It just sits forever. I guess it's because `check` starts a separate R process to run the tests, and this gets processx confused.
