### ISSUE TITLE
Args with single quotes can lose quotes on Windows

### ISSUE THREAD

**Issue by wch** [r-lib/processx#94]
It appears that, on Windows, if an argument has single quotes and a space, the quotes are preserved, but if there are single quotes and _no_ space, the quotes disappear. For example:

```R
# OK
process$new(command = "echo", args = "'a' b", stdout = "|")$read_all_output_lines()
#> [1] "'a' b"

# Wrong output
process$new(command = "echo", args = "'a'b", stdout = "|")$read_all_output_lines()
#> [1] "ab"
```

**Comment by gaborcsardi** [comment]
This looks like a bug indeed. Single quotes are not special on windows, they should be always preserved.

**Comment by jeroen** [comment]
Running into similar problem. I would like to run a command like `R -e 'print("hello world")'` but I can't get the quoting correct on windows. These both fail:

```r
processx::run(R.home('bin/R'), args = c('-e', 'print("hello world")'))
```

```r
processx::run(R.home('bin/R'), args = c('-e', "print('hello world')"))
```

**Comment by gaborcsardi** [comment]
Several issues here, I don't even know where to start. None of them are processx issues, though. :(

1. If you want to run the same arch, then you need `file.path(R.home("bin"), "R")`.

2. The above runs `R.exe` on windows, which will run another process, usually `Rterm.exe`. `R.exe` parses the arguments and passes them to `Rterm.exe`, and the parser has a bug if the string has a space. This has been fixed in R-devel, so your code (well, the second version) works there, actually. More here: http://r.789695.n4.nabble.com/command-line-arguments-are-parsed-differently-on-windows-from-3-4-3-td4747031.html

3. The parser in `R.exe` also interprets double quotes, so it is better not to use them. Or, again, use `Rterm.exe` directly, both of your versions work there, because processx/callr does not require quoting and `Rterm.exe` does not parse the arguments, just uses them.

4. Another reason why it is better to run `Rterm.exe` directly, is that otherwise killing the child process, or timeouts do not work, as the real R (=Rterm) process will be a grandchild of the original R process, and kill only kills the child.

5. `callr::r` takes care all of this for you, and it will run the correct `Rterm.exe` on Windows and `R` on non-windows.

Summary: 
* If you need to use `run()`, then use `Rterm.exe` on windows, and `R` on other platforms.
* If you can afford using `callr::r`, then just use that. (callr should have a script mode, which is equivalent to running R from the command line, I'll add that soon: https://github.com/r-lib/callr/issues/40)

## R 3.4.3:

```r
> callr::run(file.path(R.home('bin'), 'R'), args = c('-q', '-e', 'print("hello world")'))
Error in callr::run(file.path(R.home("bin"), "R"), args = c("-q", "-e",  : 
  System command error
> callr::run(file.path(R.home('bin'), 'R'), args = c('-q', '-e', "print('hello world')"))
Error in callr::run(file.path(R.home("bin"), "R"), args = c("-q", "-e",  : 
  System command error
> callr::run(file.path(R.home('bin'), 'R'), args = c('-q', '-e', "print('hello-world')"))
$status
[1] 0

$stdout
[1] "> print('hello-world')\r\n[1] \"hello-world\"\r\n> \r\n> \r\n"

$stderr
[1] ""

$timeout
[1] FALSE

> callr::run(file.path(R.home('bin'), 'Rterm'), args = c('-q', '-e', "print('hello world')"))
$status
[1] 0

$stdout
[1] "> print('hello world')\r\n[1] \"hello world\"\r\n> \r\n> \r\n"

$stderr
[1] ""

$timeout
[1] FALSE

> callr::run(file.path(R.home('bin'), 'Rterm'), args = c('-q', '-e', 'print("hello world")'))
$status
[1] 0

$stdout
[1] "> print(\"hello world\")\r\n[1] \"hello world\"\r\n> \r\n> \r\n"

$stderr
[1] ""

$timeout
[1] FALSE
```

## R-devel:

```r
> callr::run(file.path(R.home('bin'), 'R'), args = c('-q', '-e', 'print("hello world")'))
Error in callr::run(file.path(R.home("bin"), "R"), args = c("-q", "-e",  : 
  System command error
> callr::run(file.path(R.home('bin'), 'R'), args = c('-q', '-e', "print('hello world')"))
$`status`
[1] 0

$stdout
[1] "> print('hello world')\r\n[1] \"hello world\"\r\n> \r\n> \r\n"

$stderr
[1] ""

$timeout
[1] FALSE

> callr::run(file.path(R.home('bin'), 'Rterm'), args = c('-q', '-e', 'print("hello world")'))
$`status`
[1] 0

$stdout
[1] "> print(\"hello world\")\r\n[1] \"hello world\"\r\n> \r\n> \r\n"

$stderr
[1] ""

$timeout
[1] FALSE

>
```

**Comment by jeroen** [comment]
Thanks for the detailed answer. Do you mean `processx::run` instead of `callr::run`?

**Comment by gaborcsardi** [comment]
`processx` is now part of `callr`, so they are the same. 

But `processx` on CRAN is buggy and I cannot update it. `callr` is the most current on CRAN, and its `run()`, etc. have several bug fixes.

**Comment by jeroen** [comment]
OK right, I was already using the dev version of processx.

**Comment by gaborcsardi** [comment]
That should be the same as the one embedded into callr.

**Comment by gaborcsardi** [comment]
@wch I am closing this, because ideally I would not change the quoting because of one application. But feel free to discuss.

**Comment by wch** [comment]
@gaborcsardi Sounds good.
