### ISSUE TITLE
$kill should attempt soft kill first

### ISSUE THREAD

**Issue by wch** [r-lib/processx#95]
In most cases, it would be desirable to attempt a soft-kill via a `SIGTERM`, then wait before doing a `SIGKILL`.

I see that `$kill()` already has a `grace` parameter -- does this imply that the behavior I'm describing is the desired behavior?

**Comment by gaborcsardi** [comment]
Note that you can easily implement this, just send a `SIGTERM` and then `wait()` with a timeout.

**Comment by wch** [comment]
For my purposes, I'm giving a child R process SIGINT, then SIGTERM, and then SIGKILL.

In my tests, the SIGINT interrupts whatever R is doing, then the SIGTERM causes R to exit. Unfortunately, finalizers with `onexit=TRUE` don't run when the process receives a SIGTERM, and I haven't been able to figure out a way to get R to run them when the process is killed with an external signal.

R itself sends these three signals, in that order: https://github.com/wch/r-source/blob/e2de9741/src/unix/sys-unix.c#L273-L289

**Comment by gaborcsardi** [comment]
Yeah, one could argue that R should catch the SIGTERM and run the finalizers.

**Comment by gaborcsardi** [comment]
I decided not to do this, for now. The reason is that it does not play well with async programming if we wait for a single external process. Once we have a proper async event loop, then we can have an async  kill operation that sends a TERM first. 

For now, please send a TERM manually, and then `wait()`,  and `kill()` if you need to.
